title: Laboratory of Genetics of Human Immunity
email: rui.yang[at]bcm.edu
description: Yang Lab at Baylor College of Medicine and Texas Children's Hospital, studying human genetics of immunity, severe infection, immune dysregulation, malignancy, and mechanism-driven diagnosis and therapy.
url: https://ruiyanggenetics.github.io
baseurl: /ghilab

markdown: kramdown
